### PR TITLE
ARTEMIS-4780 - Allow JMX Domain to be discoverable

### PR DESCRIPTION
**Pull request by andytaylor**
This is because users can change this, the code now searched for *:broker=*

### CODE REVIEW

**Comment by gemmellr** [comment]
This feels off. The whole point of the domain in the object name is to avoid clashing, as some other component could easily have broker= in its mbean names.

I see from JIRA that this is coming up due to shading the broker. Presumably the console bits should be shaded too in that case? Is there a way the value could be taken from a file, such that shading it could [be made to] update that also?

**Comment by andytaylor** [comment]
For some reason I thought the domain was configurable so I think I agree. I will close this

**Comment by joshb1050** [comment]
The tricky piece of this is the WAR is provided separately and so we have to run a custom shader to shade it. However it doesn't rewrite the JMX domain as part of the shading process as it's just a string in a TS file.
 
I think what's unexpected is the JMXDomain is configurable as one says but the console doesn't pick up on it, hence the confusion.

Custom compilation does work changing the hardcoded value and we could do that if that's the best approach forward. Thanks for looking at this.

**Comment by andytaylor** [comment]
I have made it configurable and this time actually use it, I can reopen this or raise a new PR, wdyt?

**Comment by joshb1050** [comment]
@andytaylor Up to you—whichever makes most sense. Thanks for tackling!

**Pull request closed without merging**
